export const ADD_ITEM = 'ADD_ITEM';

export const DELETE_ITEM = 'DELETE_ITEM';

export const ENABLE_EDIT_ITEM = 'ENABLE_EDIT_ITEM';

export const SAVE_CHANGES_TO_ITEM = 'SAVE_CHANGES_TO_ITEM';

export const CANCEL_CHANGES_TO_ITEM = 'CANCEL_CHANGES_TO_ITEM';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';

export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const POST_ITEMS_SUCCESS = 'POST_ITEMS_SUCCESS';

export const POST_ITEMS_FAILURE = 'POST_ITEMS_FAILURE';

export const DISMISS_ERROR = 'DISMISS_ERROR';
